<?php

use Drupal\Core\Entity\EntityInterface;

function premium_preprocess_user(array &$variables) {
  if ($variables['elements']['#view_mode'] == 'compact') {
    $entity = $variables['user'];
    $variables['content'][] = [
      '#theme' => 'username',
      '#account' => $entity,
      '#link_options' => ['attributes' => ['rel' => 'author']],
      '#cache' => [
        'tags' => $entity->getCacheTags(),
      ],
    ];
  }
}
