<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\premium_layout_builder_restrictions\Form\FormAlter;


/**
 * Implements hook_form_FORM_ID_alter() for the entity view display edit form.
 */
function premium_layout_builder_restrictions_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter the entity view display form to set the allowed block categories.
  //\Drupal::classResolver(FormAlter::class)->alterEntityViewDisplayFormAllowedBlockCategories($form, $form_state, $form_id);
  $unique_section_restriction_active = TRUE;
  if ($config = \Drupal::config('layout_builder_restrictions.plugins')->get('plugin_config')) {
    // Provide the per view mode restriction UI *unless* the plugin is disabled.
    if (isset($config['unique_section_restriction']) && $config['unique_section_restriction']['enabled'] == FALSE) {
      $unique_section_restriction_active = FALSE;
    }
  }
  if ($unique_section_restriction_active) {
    \Drupal::classResolver(FormAlter::class)->alterEntityViewDisplayForm($form, $form_state, $form_id);
  }
}
