<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\premium_layout_builder_restrictions\Form\FormAlterBase;
use Drupal\premium_layout_builder_restrictions\ElementAlter;


/**
 * Implements hook_form_FORM_ID_alter() for the entity view display edit form.
 */
function premium_layout_builder_restrictions_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var FormAlterBase[] $form_alters */
  $form_alters = [];
  // Alter the entity view display form to set the allowed block categories.
  //\Drupal::classResolver(FormAlterBase::class)->alterEntityViewDisplayFormAllowedBlockCategories($form, $form_state, $form_id);
  /** @var \Drupal\Core\Config\Config $config */
  if ($config = \Drupal::config('layout_builder_restrictions.plugins')->get('plugin_config')) {
    // Provide the per view mode restriction UI *unless* the plugin is disabled.
    if (!isset($config['unique_section_restriction']) || $config['unique_section_restriction']['enabled'] != FALSE) {
      $form_alters[] = \Drupal::classResolver(\Drupal\premium_layout_builder_restrictions\Form\UniqueSectionFormAlter::class);
    }
    if (!isset($config['singular_block_region_restriction']) || $config['singular_block_region_restriction']['enabled'] != FALSE) {
      $form_alters[] = \Drupal::classResolver(\Drupal\premium_layout_builder_restrictions\Form\SingularBlockRegionFormAlter::class);
    }
  }
  foreach ($form_alters as $form_alter) {
    $form_alter->alterEntityViewDisplayForm($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_element_info_alter().
 */
function premium_layout_builder_restrictions_element_info_alter(array &$info) {
  if (!empty($info['layout_builder'])) {
    $info['layout_builder']['#pre_render'][] = [
      ElementAlter::class,
      'preRender',
    ];
  }
}
